networks:
  web_net:
    name: web_net
    driver: overlay

volumes:
  traefik-acme:
    name: traefik-acme

services:
  traefik:
    image: traefik:latest        
    command:
      - "--log.level=DEBUG"
      - "--log.filepath=/log-file.log"
      - "--log.format=json"
      - "--api=true"
      - "--ping=true"
      - "--accesslog=true"
      - "--accesslog.bufferingsize=100"
      - "--api.insecure=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=web_net"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--certificatesresolvers.mycert.acme.email=certs@avarancloud.ir"
      - "--certificatesresolvers.mycert.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.mycert.acme.tlschallenge=true"
      - "--providers.file.directory=/traefik"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /traefik:/traefik
      - /traefik-acme:/acme
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web_net"
        - "traefik.http.routers.traefik.entrypoints=http"
        - "traefik.http.routers.traefik.rule=Host(`traefik.avarancloud.ir`)"
        - "traefik.http.routers.traefik.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
        - "traefik.http.middlewares.web-auth.basicauth.users=avarancloud:{SHA}/7B/sSL1ebPdiHUatSOLxakVUPI="
        - "traefik.http.routers.traefik-secure.middlewares=web-auth"
        - "traefik.http.routers.traefik-secure.entrypoints=https"
        - "traefik.http.routers.traefik-secure.rule=Host(`traefik.avarancloud.ir`)"
        - "traefik.http.routers.traefik-secure.tls=true"
        - "traefik.http.routers.traefik-secure.tls.certresolver=mycert"
        - "traefik.http.routers.traefik-secure.service=api@internal"
        - "traefik.http.routers.traefik-secure.middlewares=rate-limit"
        - "traefik.http.middlewares.rate-limit.ratelimit.average=240"
        - "traefik.http.middlewares.rate-limit.ratelimit.burst=25"
        - "traefik.http.middlewares.rate-limit.ratelimit.period=1m"
        - "traefik.http.middlewares.rate-limit.ratelimit.sourcecriterion.requestheadername=X-Forwarded-For"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - web_net